"""Canonical BUILD-003 domain exports."""

from .decimal_input import (
    DECIMAL_DIGIT_LIMIT,
    DecimalInputError,
    ParsedDecimal,
    numeric_context_for,
    parse_decimal_text,
)
from .enmity import (
    ENMITY_CAP,
    ENMITY_OUTPUT_ID,
    ENMITY_OUTPUT_LABEL,
    ENMITY_TARGET_OUTPUT_ID,
    TARGET_GAME_VERSION,
    EnmityResult,
    TargetResult,
    evaluate_enmity,
)
from .flame_link import (
    ARTIFACT_ID as FLAME_LINK_ARTIFACT_ID,
    EXPECTED_ARTIFACT_ID,
    EXPECTED_FORMULA_VERSION_ID,
    EXPECTED_ROUNDING_POLICY_ID,
    EXPECTED_SOURCE_DATA_VERSION,
    EXPECTED_TABLE_ROW_COUNT,
    EXPECTED_TARGET_GAME_VERSION,
    FORMULA_VERSION_ID as FLAME_LINK_FORMULA_VERSION_ID,
    OUTPUT_ID as FLAME_LINK_OUTPUT_ID,
    OUTPUT_LABEL as FLAME_LINK_OUTPUT_LABEL,
    ROUNDING_POLICY_ID as FLAME_LINK_ROUNDING_POLICY_ID,
    SOURCE_DATA_VERSION as FLAME_LINK_SOURCE_DATA_VERSION,
    FlameLinkLevelTable,
    FlameLinkResult,
    FlameLinkTableError,
    evaluate_flame_link,
    load_flame_link_level_table,
    parse_flame_link_level_table_bytes,
    round_half_up,
    table_sha256,
)
from .player_chain_recognition import (
    RecognizedPlayerChainLine,
    recognize_player_chain_sources,
    recognize_player_chain_text,
)

__all__ = [
    "DECIMAL_DIGIT_LIMIT",
    "ENMITY_CAP",
    "ENMITY_OUTPUT_ID",
    "ENMITY_OUTPUT_LABEL",
    "ENMITY_TARGET_OUTPUT_ID",
    "EXPECTED_ARTIFACT_ID",
    "EXPECTED_FORMULA_VERSION_ID",
    "EXPECTED_ROUNDING_POLICY_ID",
    "EXPECTED_SOURCE_DATA_VERSION",
    "EXPECTED_TABLE_ROW_COUNT",
    "EXPECTED_TARGET_GAME_VERSION",
    "FLAME_LINK_ARTIFACT_ID",
    "FLAME_LINK_FORMULA_VERSION_ID",
    "FLAME_LINK_OUTPUT_ID",
    "FLAME_LINK_OUTPUT_LABEL",
    "FLAME_LINK_ROUNDING_POLICY_ID",
    "FLAME_LINK_SOURCE_DATA_VERSION",
    "TARGET_GAME_VERSION",
    "DecimalInputError",
    "EnmityResult",
    "FlameLinkLevelTable",
    "FlameLinkResult",
    "FlameLinkTableError",
    "ParsedDecimal",
    "RecognizedPlayerChainLine",
    "TargetResult",
    "evaluate_enmity",
    "evaluate_flame_link",
    "load_flame_link_level_table",
    "numeric_context_for",
    "parse_decimal_text",
    "parse_flame_link_level_table_bytes",
    "recognize_player_chain_sources",
    "recognize_player_chain_text",
    "round_half_up",
    "table_sha256",
]
